### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by nikey02** [lycstar/build_flutter_engine_arm64#1]
Please can you add readme may with example how to use it . Is it compatible with termux something like this info.
It would be helpful 
Thnx.

**Comment by lycstar** [comment]
> Please can you add readme may with example how to use it . Is it compatible with termux something like this info.
> It would be helpful
> Thnx.

this repo is not for termux, maybe you're talking about another one build_dart..., it's using github action to compile

**Comment by nikey02** [comment]
Oh i see
